# Generated by Django 4.1 on 2024-11-29 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("btitle", models.CharField(max_length=170)),
                (
                    "blogo",
                    models.ImageField(blank=True, null=True, upload_to="booklogos/"),
                ),
                ("bauthor", models.CharField(max_length=130)),
                ("bgenre", models.CharField(max_length=42)),
                ("bdescription", models.TextField()),
                (
                    "bk_requesters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="requested_bks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
